### ISSUE TITLE
not accessible externally 

### ISSUE THREAD

**Issue by heyitsfog** [isaqueprofeta/zabbix-lab#5]
I'm not sure if this is intended.. but I cant access any of the services externally.  
I've used DNS and IP address for all the ports and I get nothing.. 
If this IS intended.. how might I change that?

**Comment by isaqueprofeta** [comment]
Yes. It's working as intended since it's a lab scenario.

To change that, add the "ports" to the containers that you need to expose [Docs Here](https://docs.docker.com/compose/networking/). Another option of study to you: use the zabbix containers oficial docs.[Docs Here](https://www.zabbix.com/documentation/current/en/manual/installation/containers)
